/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/admin/complaints`; params?: Router.UnknownInputParams; } | { pathname: `/admin/notices`; params?: Router.UnknownInputParams; } | { pathname: `/admin/rooms`; params?: Router.UnknownInputParams; } | { pathname: `/admin/students`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/student/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/student/gate-pass`; params?: Router.UnknownInputParams; } | { pathname: `/student/mess-feedback`; params?: Router.UnknownInputParams; } | { pathname: `/student/notices`; params?: Router.UnknownInputParams; } | { pathname: `/student/profile`; params?: Router.UnknownInputParams; } | { pathname: `/student/room`; params?: Router.UnknownInputParams; } | { pathname: `/student/complaints`; params?: Router.UnknownInputParams; } | { pathname: `/student/complaints/new`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/complaints`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/notices`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/rooms`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/students`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/register`; params?: Router.UnknownOutputParams; } | { pathname: `/student/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/student/gate-pass`; params?: Router.UnknownOutputParams; } | { pathname: `/student/mess-feedback`; params?: Router.UnknownOutputParams; } | { pathname: `/student/notices`; params?: Router.UnknownOutputParams; } | { pathname: `/student/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/student/room`; params?: Router.UnknownOutputParams; } | { pathname: `/student/complaints`; params?: Router.UnknownOutputParams; } | { pathname: `/student/complaints/new`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin/dashboard${`?${string}` | `#${string}` | ''}` | `/admin/complaints${`?${string}` | `#${string}` | ''}` | `/admin/notices${`?${string}` | `#${string}` | ''}` | `/admin/rooms${`?${string}` | `#${string}` | ''}` | `/admin/students${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/register${`?${string}` | `#${string}` | ''}` | `/student/dashboard${`?${string}` | `#${string}` | ''}` | `/student/gate-pass${`?${string}` | `#${string}` | ''}` | `/student/mess-feedback${`?${string}` | `#${string}` | ''}` | `/student/notices${`?${string}` | `#${string}` | ''}` | `/student/profile${`?${string}` | `#${string}` | ''}` | `/student/room${`?${string}` | `#${string}` | ''}` | `/student/complaints${`?${string}` | `#${string}` | ''}` | `/student/complaints/new${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/admin/complaints`; params?: Router.UnknownInputParams; } | { pathname: `/admin/notices`; params?: Router.UnknownInputParams; } | { pathname: `/admin/rooms`; params?: Router.UnknownInputParams; } | { pathname: `/admin/students`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/student/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/student/gate-pass`; params?: Router.UnknownInputParams; } | { pathname: `/student/mess-feedback`; params?: Router.UnknownInputParams; } | { pathname: `/student/notices`; params?: Router.UnknownInputParams; } | { pathname: `/student/profile`; params?: Router.UnknownInputParams; } | { pathname: `/student/room`; params?: Router.UnknownInputParams; } | { pathname: `/student/complaints`; params?: Router.UnknownInputParams; } | { pathname: `/student/complaints/new`; params?: Router.UnknownInputParams; };
    }
  }
}
